### ISSUE TITLE
TypeError: Error while loading rule 'perfectionist/sort-imports': sourceCode.getAllComments is not a function on markdown files since v7.5.0

### ISSUE THREAD

**Issue by kevinmarrec** [antfu/.github#8]
### Describe the bug

After upgrading `@antfu/eslint-config` from `7.4.3` to `7.6.1`, ESLint crashes with a `TypeError` when linting markdown files (e.g. `README.md`).

The crash originates from the `perfectionist/sort-imports` rule. Its internal `getEslintDisabledLines` utility calls `sourceCode.getAllComments()`, which does not exist on the `@eslint/markdown` SourceCode object introduced by the "markdown: Use markdown language" change in v7.5.0 ([`9306355`](https://github.com/antfu/eslint-config/commit/9306355)).

This happens with the **default config** — no custom markdown language configuration is needed to trigger it.

```
Oops! Something went wrong! :(

ESLint: 9.39.3

TypeError: Error while loading rule 'perfectionist/sort-imports': sourceCode.getAllComments is not a function
Occurred while linting /home/runner/work/config/config/README.md
    at getEslintDisabledLines (file:///...)
    at create (file:///...)
    at Object.create (...)
    at createRuleListeners (...)
    ...
```

### Reproduction

```ts
import antfu from '@antfu/eslint-config'

export default antfu()
```

Then run `eslint .` on any project that contains a `README.md`.

- ✅ Works on `@antfu/eslint-config@7.4.3`
- ❌ Crashes on `@antfu/eslint-config@7.5.0` and later (tested `7.6.1`)

### Expected behavior

Markdown files should be excluded from rules that rely on JS-specific SourceCode APIs (like `getAllComments()`), or the rules should gracefully handle non-JS SourceCode objects without crashing.

### Related

- #806 — Similar `sourceCode.getAllComments is not a function` crash on markdown files, but triggered by explicit `markdown/gfm` language configuration
- #818 — PR that introduced the markdown language change

### Important notice

This issue description has mostly been generated by Claude Opus 4.6 with context given by me.

### Reproduction

https://github.com/kevinmarrec/config/pull/93

### System Info

```Shell
- `@antfu/eslint-config`: `7.6.1`
- `eslint`: `9.39.3`
- `eslint-plugin-perfectionist`: `5.6.0` (resolved transitively)
- Runtime: Bun 1.3.6
- OS: Ubuntu (GitHub Actions `ubuntu-latest`)
```

### Used Package Manager

bun

### Validations

- [x] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by kevinmarrec** [comment]
Sorry wrong repository, GitHub Mobile app from Eslint Config repository pointed me to this in my browser and got trapped 😅
